new-crates-to-check = "30d"

[allowed-crates]
maplit2 = ["maplit"]
no-std-compat2 = ["no-std-compat"]
eusb = ["rusb"]

[typos]
'1' = ['2', 'q', 'i', 'l']
'2' = ['1', 'q', 'w', '3']
'3' = ['2', 'w', 'e', '4']
'4' = ['3', 'e', 'r', '5']
'5' = ['4', 'r', 't', '6', 's']
'6' = ['5', 't', 'y', '7']
'7' = ['6', 'y', 'u', '8']
'8' = ['7', 'u', 'i', '9']
'9' = ['8', 'i', 'o', '0']
'0' = ['9', 'o', 'p', '-']
'-' = ['_', '0', 'p', '.', '']
'_' = ['-', '0', 'p', '.', '']
'q' = ['1', '2', 'w', 'a']
'w' = ['2', '3', 'e', 's', 'a', 'q', 'vv']
'e' = ['3', '4', 'r', 'd', 's', 'w']
'r' = ['4', '5', 't', 'f', 'd', 'e']
't' = ['5', '6', 'y', 'g', 'f', 'r']
'y' = ['6', '7', 'u', 'h', 't', 'i']
'u' = ['7', '8', 'i', 'j', 'y', 'v']
'i' = ['1', '8', '9', 'o', 'l', 'k', 'j', 'u', 'y']
'o' = ['9', '0', 'p', 'l', 'i']
'p' = ['0', '-', 'o']
'a' = ['q', 'w', 's', 'z']
's' = ['w', 'd', 'x', 'z', 'a', '5']
'd' = ['e', 'r', 'f', 'c', 'x', 's']
'f' = ['r', 'g', 'v', 'c', 'd']
'g' = ['t', 'h', 'b', 'v', 'f']
'h' = ['y', 'j', 'n', 'b', 'g']
'j' = ['u', 'i', 'k', 'm', 'n', 'h']
'k' = ['i', 'o', 'l', 'm', 'j']
'l' = ['i', 'o', 'p', 'k', '1']
'z' = ['a', 's', 'x']
'x' = ['z', 's', 'd', 'c']
'c' = ['x', 'd', 'f', 'v']
'v' = ['c', 'f', 'g', 'b', 'u']
'b' = ['v', 'g', 'h', 'n']
'n' = ['b', 'h', 'j', 'm']
'm' = ['n', 'j', 'k', 'rn']
'.' = ['-', '_', '']
